import * as Joi from 'joi';

export const envSchema = Joi.object({
  NODE_ENV: Joi.string().valid('development', 'test', 'production').default('development'),
  PORT: Joi.number().default(3001),
  DATABASE_URL: Joi.string().required(),
  REDIS_URL: Joi.string().default('redis://localhost:6379'),
  LOG_LEVEL: Joi.string().valid('fatal', 'error', 'warn', 'info', 'debug', 'trace').default('info'),
  CORS_ORIGINS: Joi.string().allow('').default(''),
  JWT_SECRET: Joi.string().required(),
  TOKEN_TTL: Joi.number().integer().min(60).default(900),
  REFRESH_TTL: Joi.number().integer().min(300).default(2592000),
  ORDER_PAYMENT_TTL_SECONDS: Joi.number().integer().min(60).default(900),
  ORDER_AUTO_COMPLETE_HOURS: Joi.number().integer().min(1).default(72),
  PIX_MOCK_MODE: Joi.string().valid('true', 'false').default('true'),
  PIX_MOCK_TTL_SECONDS: Joi.number().integer().min(60).default(900),
  EFI_CLIENT_ID: Joi.string(),
  EFI_CLIENT_SECRET: Joi.string(),
  EFI_CERT_PATH: Joi.string(),
  EFI_ENV: Joi.string().valid('sandbox', 'prod').default('sandbox'),
  EFI_PIX_KEY: Joi.string(),
  EFI_WEBHOOK_SKIP_MTLS_CHECKING: Joi.string().valid('true', 'false').default('false'),
  SETTLEMENT_MODE: Joi.string().valid('cashout', 'split').default('cashout'),
  SETTLEMENT_RELEASE_DELAY_HOURS: Joi.number().integer().min(0).default(0),
  NEXT_PUBLIC_APP_URL: Joi.string().default('http://localhost:3000'),
  SENDGRID_API_KEY: Joi.string().required(),
  SENDGRID_FROM_EMAIL: Joi.string().required(),
  SENDGRID_FROM_NAME: Joi.string().allow('').default(''),
  TWILIO_ACCOUNT_SID: Joi.string().required(),
  TWILIO_AUTH_TOKEN: Joi.string().required(),
  TWILIO_VERIFY_SERVICE_SID: Joi.string().required(),
  TWILIO_SMS_FROM: Joi.string(),
  TWILIO_MESSAGING_SERVICE_SID: Joi.string(),
  TWILIO_WHATSAPP_FROM: Joi.string(),
  DISCORD_CLIENT_ID: Joi.string().required(),
  DISCORD_CLIENT_SECRET: Joi.string().required(),
  DISCORD_REDIRECT_URI: Joi.string().required(),
  GOOGLE_CLIENT_ID: Joi.string().required(),
  GOOGLE_CLIENT_SECRET: Joi.string().required(),
  GOOGLE_REDIRECT_URI: Joi.string().required(),
  GEMINI_API_KEY: Joi.string().required(),
  GEMINI_MODEL: Joi.string().default('gemini-2.5-flash'),
  SUPPORT_AI_ENABLED: Joi.string().valid('true', 'false').default('true'),
}).or('TWILIO_SMS_FROM', 'TWILIO_MESSAGING_SERVICE_SID');
